version: '3.7'

services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.excalidraw.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.excalidraw.entrypoints: websecure
      traefik.http.routers.excalidraw.service: excalidraw
      traefik.http.routers.excalidraw.tls.certresolver: myresolver
      traefik.http.services.excalidraw.loadbalancer.server.port: 80
