version: "3.7"

services:
  barrage:
    image: maulik9898/barrage:0.3.0
    container_name: barrage
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DELUGE_URL=${DELUGE_URL}
      - DELUGE_PASSWORD=${DELUGE_PASSWORD}
      - BARRAGE_PASSWORD=${BARRAGE_PASSWORD}
    ports:
      - ${APP_PORT}:3000
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.barrage.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.barrage.entrypoints: websecure
      traefik.http.routers.barrage.service: barrage
      traefik.http.routers.barrage.tls.certresolver: myresolver
      traefik.http.services.barrage.loadbalancer.server.port: 3000
