version: "3"

services:
  grav:
    container_name: grav
    image: lscr.io/linuxserver/grav:1.7.39.4-ls97
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/grav-comfig:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.grav.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grav.entrypoints: websecure
      traefik.http.routers.grav.service: grav
      traefik.http.routers.grav.tls.certresolver: myresolver
      traefik.http.services.grav.loadbalancer.server.port: 80