version: "3"

services:
  deemix:
    container_name: deemix
    image: registry.gitlab.com/bockiii/deemix-docker
    ports:
      - ${APP_PORT}:6595
    volumes:
      - ${APP_DATA_DIR}/data/deemix-config:/config
      - ${ROOT_FOLDER_HOST}/media:/media
      - ${ROOT_FOLDER_HOST}/media/data/torrents/deemix:/downloads
      - ${ROOT_FOLDER_HOST}/media/data/music:/music
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.deemix.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.deemix.entrypoints: websecure
      traefik.http.routers.deemix.service: deemix
      traefik.http.routers.deemix.tls.certresolver: myresolver
      traefik.http.services.deemix.loadbalancer.server.port: 6595