version: "3"

services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.it-tools.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.it-tools.entrypoints: websecure
      traefik.http.routers.it-tools.service: it-tools
      traefik.http.routers.it-tools.tls.certresolver: myresolver
      traefik.http.services.it-tools.loadbalancer.server.port: 80

