version: '3.7'

services:
  dailytxt:
    image: phitux/dailytxt:1.0.12
    container_name: dailytxt
    restart: unless-stopped
    environment:
      - PORT=8765
      - SECRET_KEY=${DAILYTXT_SECRET_KEY}
      - ALLOW_REGISTRATION=${DAILYTXT_ALLOW_REGISTRATION}
      - DATA_INDENT=2
      - JWT_EXP_DAYS=60
      - ENABLE_UPDATE_CHECK=True
    ports:
      - ${APP_PORT}:8765
    volumes:
      - '${APP_DATA_DIR}/data/dailytxt:/app/data/'
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.dailytxt.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.dailytxt.entrypoints: websecure
      traefik.http.routers.dailytxt.service: dailytxt
      traefik.http.routers.dailytxt.tls.certresolver: myresolver
      traefik.http.services.dailytxt.loadbalancer.server.port: 8765
