version: '3.7'

services:
  zipline:
    container_name: zipline
    image: ghcr.io/diced/zipline:trunk-3.7.0-rc5
    ports:
      - '${APP_PORT}:3000'
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=${ZIPLINE_CORE_SECRET}
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://tipi:${ZIPLINE_DB_PASSWORD}@zipline-db/zipline
      - CORE_LOGGER=true
    volumes:
      - '${APP_DATA_DIR}/data/uploads:/zipline/uploads'
      - '${APP_DATA_DIR}/data/public:/zipline/public'
    depends_on:
      - 'zipline-db'
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.zipline.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.zipline.entrypoints: websecure
      traefik.http.routers.zipline.service: zipline
      traefik.http.routers.zipline.tls.certresolver: myresolver
      traefik.http.services.zipline.loadbalancer.server.port: 3000
    networks:
      - tipi_main_network

  zipline-db:
    container_name: zipline-db
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=${ZIPLINE_DB_PASSWORD}
      - POSTGRES_DB=zipline
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
